Repository google/cloud-forensics-utils, pull requests merged in 2020-07, with the labels that each got.

#188 pump version after pr 169
  libcloudforensics/__init__.py
Labels: cla: yes

#186 Add missing Optional type hint where possible
  examples/aws_cli.py
  libcloudforensics/providers/aws/internal/account.py
  libcloudforensics/providers/gcp/internal/compute.py
  libcloudforensics/providers/gcp/internal/compute_base_resource.py
  libcloudforensics/providers/gcp/internal/storage.py
  tests/providers/aws/aws_e2e.py
  tests/providers/aws/aws_test.py
Labels: cla: yes

#191 Initial skeleton for documentation
  docs/Makefile
  docs/conf.py
  docs/index.rst
  docs/make.bat
  docs/requirements.txt
  docs/source/libcloudforensics.providers.aws.internal.rst
  docs/source/libcloudforensics.providers.aws.rst
  docs/source/libcloudforensics.providers.gcp.internal.rst
  docs/source/libcloudforensics.providers.gcp.rst
  docs/source/libcloudforensics.scripts.rst
  requirements-dev.txt
Labels: cla: yes

#187 Remove unnecessary # type: ignore comments
  examples/cli.py
  examples/gcp_cli.py
  libcloudforensics/providers/aws/internal/account.py
  libcloudforensics/providers/aws/internal/ebs.py
  libcloudforensics/providers/gcp/forensics.py
  libcloudforensics/providers/gcp/internal/compute.py
  libcloudforensics/providers/gcp/internal/compute_base_resource.py
  libcloudforensics/providers/gcp/internal/project.py
  tests/providers/gcp/gcp_e2e.py
  tests/providers/gcp/gcp_test.py
Labels: cla: yes

#195 Addresses a tiny bug in checking the number of volumes to attach (fixes #190)
  examples/aws_cli.py
Labels: cla: yes

#198 Initial Documentation PR
  docs/Makefile
  docs/conf.py
  docs/gettingstarted.md
  docs/index.md
  docs/make.bat
  docs/requirements.txt
  docs/source/libcloudforensics.providers.aws.internal.rst
  docs/source/libcloudforensics.providers.aws.rst
  docs/source/libcloudforensics.providers.gcp.internal.rst
  docs/source/libcloudforensics.providers.gcp.rst
  docs/source/libcloudforensics.scripts.rst
  docs/usermanual/index.md
  requirements-dev.txt
Labels: cla: yes

#196 Add GetBucketACLs and ListBucketObjects
  examples/cli.py
  examples/gcp_cli.py
  libcloudforensics/providers/gcp/forensics.py
  libcloudforensics/providers/gcp/internal/build.py
  libcloudforensics/providers/gcp/internal/storage.py
  tests/providers/gcp/gcp_test.py
Labels: M, cla: yes

#180 Add --start and --end to GCP log query functionality
  examples/cli.py
  examples/gcp_cli.py
Labels: GCP, S, cla: yes

#194 Replace regex string length by len()
  libcloudforensics/providers/aws/internal/account.py
  libcloudforensics/providers/aws/internal/common.py
  libcloudforensics/providers/aws/internal/ebs.py
Labels: S, cla: yes, cleanup

#193 Migrate from self.assertRaise to context manager in unit tests
  tests/providers/aws/aws_test.py
  tests/providers/gcp/gcp_test.py
Labels: S, cla: yes, cleanup

#200 Add missing option to AWS CLI
  examples/aws_cli.py
  examples/cli.py
Labels: AWS, S, cla: yes

#192 Default value for optional string parameters should be None
  libcloudforensics/providers/aws/forensics.py
  libcloudforensics/providers/aws/internal/account.py
  libcloudforensics/providers/aws/internal/ebs.py
  libcloudforensics/providers/gcp/internal/compute.py
Labels: S, cla: yes, cleanup

#174 Forensic disk copy capabilities in Azure
  examples/az_cli.py
  libcloudforensics/providers/azure/__init__.py
  libcloudforensics/providers/azure/forensics.py
  libcloudforensics/providers/azure/internal/__init__.py
  libcloudforensics/providers/azure/internal/account.py
  libcloudforensics/providers/azure/internal/common.py
  libcloudforensics/providers/azure/internal/compute.py
  requirements.txt
  tests/providers/azure/__init__.py
  tests/providers/azure/azure_e2e.py
  tests/providers/azure/azure_test.py
Labels: Azure, XL, cla: yes

#197 create images from compressed archived GCE images (.tar.gz) in GCS
  libcloudforensics/providers/gcp/internal/common.py
  libcloudforensics/providers/gcp/internal/compute.py
  tests/providers/gcp/gcp_test.py
Labels: S, cla: yes

#203 Add authentication through access key for AWS
  libcloudforensics/providers/aws/internal/account.py
  tests/providers/aws/aws_test.py
Labels: AWS, S, cla: yes, enhancement

#185 Add e2e tests for Azure snapshotting capabilities
  tests/providers/azure/azure_e2e.py
Labels: Azure, M, cla: yes

#199 Add AWS documentation
  docs/source/images/ebs.png
  docs/usermanual/index.md
Labels: AWS, M, cla: yes, documentation

#204 Add custom logger and add more logging
  libcloudforensics/logging_utils.py
  libcloudforensics/providers/aws/forensics.py
  libcloudforensics/providers/aws/internal/common.py
  libcloudforensics/providers/gcp/forensics.py
  libcloudforensics/providers/gcp/internal/build.py
  libcloudforensics/providers/gcp/internal/common.py
  libcloudforensics/providers/gcp/internal/compute.py
  libcloudforensics/providers/gcp/internal/function.py
  tests/providers/aws/aws_e2e.py
  tests/providers/gcp/gcp_e2e.py
Labels: M, cla: yes, cleanup, enhancement

#209 Fix link in AWS documentation
  docs/usermanual/index.md
Labels: cla: yes

#205 Adding GKE APIs and Cluster Get Operation
  libcloudforensics/providers/gcp/internal/gke.py
  libcloudforensics/providers/gcp/internal/project.py
  tests/providers/gcp/gcp_test.py
Labels: GCP, M, cla: yes

#213 Add Microsoft Azure disk snapshotting capabilities
  examples/az_cli.py
  examples/cli.py
  libcloudforensics/providers/azure/__init__.py
  libcloudforensics/providers/azure/forensics.py
  libcloudforensics/providers/azure/internal/__init__.py
  libcloudforensics/providers/azure/internal/account.py
  libcloudforensics/providers/azure/internal/common.py
  libcloudforensics/providers/azure/internal/compute.py
  requirements.txt
  tests/providers/azure/__init__.py
  tests/providers/azure/azure_e2e.py
  tests/providers/azure/azure_test.py
  tests/scripts/test_credentials.json
Labels: Azure, cla: yes, enhancement

#214 bump version
  libcloudforensics/__init__.py
Labels: cla: yes

#211 Add AWS CLI flag to generate an SSH key for startvm
  examples/aws_cli.py
  examples/cli.py
  libcloudforensics/providers/aws/internal/account.py
  libcloudforensics/providers/gcp/internal/gke.py
Labels: AWS, S, cla: yes, enhancement

#228 Fix github setup.py workflow
  .github/workflows/install_test_setup_py.yml
Labels: cla: yes

#215 Add Azure VM functionality
  libcloudforensics/providers/azure/forensics.py
  libcloudforensics/providers/azure/internal/account.py
  libcloudforensics/providers/azure/internal/compute.py
  requirements.txt
Labels: Azure, L, cla: yes, enhancement

#206 Add Azure Monitoring metrics
  examples/az_cli.py
  examples/cli.py
  libcloudforensics/providers/azure/internal/monitoring.py
  requirements.txt
  tests/providers/azure/azure_test.py
Labels: Azure, M, cla: yes, enhancement

#230 Fix format string in logger
  libcloudforensics/providers/aws/forensics.py
Labels: AWS, S, bug, cla: yes

#227 Renaming "example" directory to "tools"
  .github/workflows/pylint_and_mypy.yml
  README.md
  docs/gettingstarted.md
  setup.py
  tools/__init__.py
  tools/aws_cli.py
  tools/az_cli.py
  tools/cli.py
  tools/gcp_cli.py
Labels: S, cla: yes, cleanup

#218 Replace print statements by call to logger in CLI tool
  tools/aws_cli.py
  tools/gcp_cli.py
Labels: S, cla: yes, cleanup

#232 Add Azure VM capabilities
  libcloudforensics/providers/azure/forensics.py
  libcloudforensics/providers/azure/internal/account.py
  libcloudforensics/providers/azure/internal/compute.py
  requirements.txt
  tests/providers/azure/azure_e2e.py
  tests/providers/azure/azure_test.py
  tools/az_cli.py
  tools/cli.py
Labels: Azure, cla: yes, enhancement

#219 Default disk type to source disk type in CreateDiskCopy
  libcloudforensics/providers/azure/forensics.py
  libcloudforensics/providers/azure/internal/account.py
  libcloudforensics/providers/azure/internal/compute.py
  libcloudforensics/providers/gcp/forensics.py
  libcloudforensics/providers/gcp/internal/compute.py
  tests/providers/azure/azure_test.py
  tests/providers/gcp/gcp_test.py
  tools/cli.py
  tools/gcp_cli.py
Labels: Azure, GCP, S, cla: yes, enhancement
