Repository google/cloud-forensics-utils, pull requests merged in 2020-06, with the labels that each got.

#109 Add global CLI tool for libcloudforensics
  examples/aws_cli.py
  examples/gcp_cli.py
  examples/libcloudforensics.py
  setup.py
Labels: cla: yes

#111 Refactor
  libcloudforensics/providers/gcp/forensics.py
  libcloudforensics/providers/gcp/internal/build.py
  libcloudforensics/providers/gcp/internal/common.py
  libcloudforensics/providers/gcp/internal/compute.py
  libcloudforensics/providers/gcp/internal/compute_resources.py
  libcloudforensics/providers/gcp/internal/function.py
  libcloudforensics/providers/gcp/internal/project.py
Labels: cla: no

#112 Fix gcp unit and e2e tests
  examples/gcp_cli.py
  libcloudforensics/providers/gcp/internal/build.py
  libcloudforensics/providers/gcp/internal/common.py
  libcloudforensics/providers/gcp/internal/compute.py
  libcloudforensics/providers/gcp/internal/compute_resources.py
  libcloudforensics/providers/gcp/internal/function.py
  tests/providers/gcp/gcp_e2e.py
  tests/providers/gcp/gcp_test.py
Labels: cla: yes

#113 Add Paginate method for GCP
  libcloudforensics/providers/gcp/internal/common.py
  libcloudforensics/providers/gcp/internal/compute.py
  libcloudforensics/providers/gcp/internal/log.py
Labels: cla: yes

#114 Rename ExecuteAndPaginate to ExecuteRequest
  libcloudforensics/providers/aws/internal/account.py
  libcloudforensics/providers/aws/internal/common.py
  libcloudforensics/providers/aws/internal/log.py
Labels: cla: yes

#115 Global refactor of Libcloudforensics
  examples/aws_cli.py
  examples/gcp_cli.py
  libcloudforensics/aws.py
  libcloudforensics/gcp.py
  libcloudforensics/providers/__init__.py
  libcloudforensics/providers/aws/__init__.py
  libcloudforensics/providers/aws/forensics.py
  libcloudforensics/providers/aws/internal/__init__.py
  libcloudforensics/providers/aws/internal/account.py
  libcloudforensics/providers/aws/internal/common.py
  libcloudforensics/providers/aws/internal/ebs.py
  libcloudforensics/providers/aws/internal/ec2.py
  libcloudforensics/providers/aws/internal/log.py
  libcloudforensics/providers/gcp/__init__.py
  libcloudforensics/providers/gcp/forensics.py
  libcloudforensics/providers/gcp/internal/__init__.py
  libcloudforensics/providers/gcp/internal/build.py
  libcloudforensics/providers/gcp/internal/common.py
  libcloudforensics/providers/gcp/internal/compute.py
  libcloudforensics/providers/gcp/internal/compute_resources.py
  libcloudforensics/providers/gcp/internal/function.py
  libcloudforensics/providers/gcp/internal/log.py
  libcloudforensics/providers/gcp/internal/project.py
  libcloudforensics/scripts/__init__.py
  libcloudforensics/scripts/utils.py
  tests/providers/__init__.py
  tests/providers/aws/__init__.py
  tests/providers/aws/aws_e2e.py
  tests/providers/aws/aws_test.py
  tests/providers/gcp/__init__.py
  tests/providers/gcp/gcp_e2e.py
  tests/providers/gcp/gcp_test.py
  tests/scripts/__init__.py
  tests/scripts/startup.sh
  tests/scripts/utils.py
Labels: cla: yes

#119 Add option to copy volume in a different destination region in AWS
  examples/aws_cli.py
  examples/libcloudforensics.py
  libcloudforensics/providers/aws/forensics.py
  libcloudforensics/providers/aws/internal/account.py
  libcloudforensics/providers/aws/internal/ebs.py
  tests/providers/aws/aws_test.py
Labels: cla: yes

#122 Add SSH key option to StartAnalysisVm()
  libcloudforensics/providers/aws/forensics.py
  libcloudforensics/providers/aws/internal/account.py
  tests/providers/aws/aws_e2e.py
Labels: cla: yes

#117 Refactor attach_disk / attach_volume to list of volume names / ids
  libcloudforensics/providers/aws/forensics.py
  libcloudforensics/providers/gcp/forensics.py
  tests/providers/aws/aws_e2e.py
  tests/providers/gcp/gcp_e2e.py
Labels: cla: yes

#124 Improve unit tests with assert_called* statements
  tests/providers/aws/aws_test.py
  tests/providers/gcp/gcp_test.py
Labels: cla: yes

#125 Refactor try/except blocks
  libcloudforensics/providers/aws/internal/account.py
  libcloudforensics/providers/aws/internal/common.py
  libcloudforensics/providers/aws/internal/ec2.py
  tests/providers/aws/aws_e2e.py
Labels: cla: yes

#116 Migrate src/dst_account to src/dst_profile in AWS
  examples/aws_cli.py
  examples/libcloudforensics.py
  libcloudforensics/providers/aws/forensics.py
Labels: cla: yes

#130 Add DetachDisk method to GCP
  libcloudforensics/providers/gcp/internal/compute_resources.py
Labels: GCP, cla: yes

#133 Fix CreateVolumeCopy() dst_zone
  libcloudforensics/providers/aws/forensics.py
Labels: cla: yes

#134 Bump version
  libcloudforensics/__init__.py
Labels: cla: yes

#136 Merge part of compute_resources.py to compute.py to solve cyclic import
  libcloudforensics/providers/gcp/internal/compute.py
  libcloudforensics/providers/gcp/internal/compute_base_resource.py
  libcloudforensics/providers/gcp/internal/compute_resources.py
  tests/providers/gcp/gcp_e2e.py
  tests/providers/gcp/gcp_test.py
Labels: cla: yes

#137 Bump version
  libcloudforensics/__init__.py
Labels: cla: yes

#126 Enhance e2e tests
  tests/providers/aws/aws_e2e.py
Labels: cla: yes

#129 Change type declaration in docstrings following l2t style guide
  examples/aws_cli.py
  examples/gcp_cli.py
  examples/libcloudforensics.py
  libcloudforensics/providers/aws/forensics.py
  libcloudforensics/providers/aws/internal/account.py
  libcloudforensics/providers/aws/internal/common.py
  libcloudforensics/providers/aws/internal/ec2.py
  libcloudforensics/providers/aws/internal/log.py
  libcloudforensics/providers/gcp/internal/build.py
  libcloudforensics/providers/gcp/internal/common.py
  libcloudforensics/providers/gcp/internal/compute.py
  libcloudforensics/providers/gcp/internal/function.py
  libcloudforensics/providers/gcp/internal/log.py
Labels: cla: yes

#139 Change return type of GoogleComputeInstance.ListDisks()
  libcloudforensics/providers/gcp/internal/compute.py
  tests/providers/gcp/gcp_e2e.py
  tests/providers/gcp/gcp_test.py
Labels: cla: yes

#140 Bump version
  libcloudforensics/__init__.py
Labels: cla: yes

#142 Add disk_name option to gcp_cli
  examples/gcp_cli.py
  examples/libcloudforensics.py
Labels: cla: yes

#150 Add CODEOWNERS
  CODEOWNERS
Labels: cla: yes

#156 Bump version
  libcloudforensics/__init__.py
Labels: cla: yes

#151 Avoid naming conflict with package
  examples/cli.py
  setup.py
Labels: cla: yes

#146 Make AWS tagging more generic
  examples/aws_cli.py
  examples/cli.py
  libcloudforensics/providers/aws/forensics.py
  libcloudforensics/providers/aws/internal/account.py
  libcloudforensics/providers/aws/internal/common.py
  libcloudforensics/providers/aws/internal/ebs.py
  libcloudforensics/providers/aws/internal/ec2.py
  tests/providers/aws/aws_test.py
Labels: cla: yes

#162 Fix argname in gcp cli
  examples/gcp_cli.py
Labels: cla: yes

#163 Fix tags argument in AWS CLI
  examples/aws_cli.py
Labels: cla: yes

#160 Expose StartVM functionality through CLI.
  examples/aws_cli.py
  examples/cli.py
  examples/gcp_cli.py
Labels: cla: yes

#166 Add AMI ListImages to AWS API
  examples/aws_cli.py
  examples/cli.py
  libcloudforensics/providers/aws/internal/account.py
  tests/providers/aws/aws_e2e.py
  tests/providers/aws/aws_test.py
Labels: cla: yes

#161 Add Google Metrics API
  examples/cli.py
  examples/gcp_cli.py
  libcloudforensics/providers/gcp/internal/common.py
  libcloudforensics/providers/gcp/internal/monitoring.py
  libcloudforensics/providers/gcp/internal/project.py
  tests/providers/gcp/gcp_test.py
Labels: cla: yes

#168 Make StartVm pick right AMI per zone.
  examples/aws_cli.py
  examples/cli.py
  libcloudforensics/providers/aws/forensics.py
  libcloudforensics/providers/aws/internal/common.py
Labels: cla: yes

#176 Bump version
  libcloudforensics/__init__.py
Labels: cla: yes

#170 Update GCF API version to stable
  libcloudforensics/providers/gcp/internal/function.py
Labels: cla: yes

#178 Bump version
  libcloudforensics/__init__.py
Labels: cla: yes

#169 Import Disks From GCS ++
  examples/cli.py
  examples/gcp_cli.py
  libcloudforensics/providers/gcp/forensics.py
  libcloudforensics/providers/gcp/internal/build.py
  libcloudforensics/providers/gcp/internal/common.py
  libcloudforensics/providers/gcp/internal/compute.py
  libcloudforensics/providers/gcp/internal/compute_base_resource.py
  libcloudforensics/providers/gcp/internal/function.py
  libcloudforensics/providers/gcp/internal/log.py
  libcloudforensics/providers/gcp/internal/project.py
  libcloudforensics/providers/gcp/internal/storage.py
  tests/providers/gcp/gcp_test.py
Labels: cla: yes
