Repository google/cloud-forensics-utils, pull requests merged in 2020-08, with the labels that each got.

#235 Bump version
  libcloudforensics/__init__.py
Labels: cla: yes

#221 Add support for volume type selection in AWS
  libcloudforensics/providers/aws/forensics.py
  libcloudforensics/providers/aws/internal/account.py
  libcloudforensics/providers/aws/internal/ebs.py
  tests/providers/aws/aws_test.py
  tools/aws_cli.py
  tools/cli.py
Labels: AWS, S, cla: yes, enhancement

#234 Refactor Azure module
  libcloudforensics/providers/azure/forensics.py
  libcloudforensics/providers/azure/internal/account.py
  libcloudforensics/providers/azure/internal/common.py
  libcloudforensics/providers/azure/internal/compute.py
  libcloudforensics/providers/azure/internal/compute_base_resource.py
  libcloudforensics/providers/azure/internal/monitoring.py
  libcloudforensics/providers/azure/internal/network.py
  libcloudforensics/providers/azure/internal/resource.py
  libcloudforensics/providers/azure/internal/storage.py
  tests/providers/azure/azure_e2e.py
  tests/providers/azure/azure_test.py
  tools/az_cli.py
Labels: Azure, XL, cla: yes, cleanup

#237 Fix e2e tests in Azure
  tests/providers/azure/azure_e2e.py
Labels: Azure, S, bug, cla: yes

#225 Refactor AWS module
  libcloudforensics/providers/aws/forensics.py
  libcloudforensics/providers/aws/internal/account.py
  libcloudforensics/providers/aws/internal/ebs.py
  libcloudforensics/providers/aws/internal/ec2.py
  libcloudforensics/providers/aws/internal/kms.py
  tests/providers/aws/aws_e2e.py
  tests/providers/aws/aws_test.py
  tools/aws_cli.py
Labels: AWS, XL, cla: yes, cleanup

#236 Auto-create network security group when VM is created in Azure
  libcloudforensics/providers/azure/internal/network.py
  tests/providers/azure/azure_e2e.py
Labels: Azure, S, cla: yes, enhancement

#223 Add custom error class
  libcloudforensics/errors.py
  libcloudforensics/providers/aws/forensics.py
  libcloudforensics/providers/aws/internal/ebs.py
  libcloudforensics/providers/aws/internal/ec2.py
  libcloudforensics/providers/aws/internal/kms.py
  libcloudforensics/providers/azure/forensics.py
  libcloudforensics/providers/azure/internal/common.py
  libcloudforensics/providers/azure/internal/compute.py
  libcloudforensics/providers/azure/internal/compute_base_resource.py
  libcloudforensics/providers/azure/internal/network.py
  libcloudforensics/providers/azure/internal/storage.py
  libcloudforensics/providers/gcp/forensics.py
  libcloudforensics/providers/gcp/internal/common.py
  libcloudforensics/providers/gcp/internal/compute.py
  libcloudforensics/providers/gcp/internal/gke.py
  tests/providers/aws/aws_test.py
  tests/providers/azure/azure_test.py
  tests/providers/gcp/gcp_test.py
Labels: M, cla: yes, cleanup, enhancement

#241 Add Azure user manual in documentation
  docs/source/images/sas.png
  docs/usermanual/index.md
Labels: Azure, M, cla: yes, documentation

#233 Refactor tests module
  tests/providers/aws/aws_mocks.py
  tests/providers/aws/aws_test.py
  tests/providers/aws/e2e.py
  tests/providers/aws/internal/__init__.py
  tests/providers/aws/internal/test_common.py
  tests/providers/aws/internal/test_ebs.py
  tests/providers/aws/internal/test_ec2.py
  tests/providers/aws/internal/test_log.py
  tests/providers/aws/test_forensics.py
  tests/providers/azure/azure_mocks.py
  tests/providers/azure/azure_test.py
  tests/providers/azure/e2e.py
  tests/providers/azure/internal/__init__.py
  tests/providers/azure/internal/test_common.py
  tests/providers/azure/internal/test_compute.py
  tests/providers/azure/internal/test_monitoring.py
  tests/providers/azure/internal/test_resource.py
  tests/providers/azure/internal/test_storage.py
  tests/providers/azure/test_forensics.py
  tests/providers/gcp/e2e.py
  tests/providers/gcp/gcp_mocks.py
  tests/providers/gcp/gcp_test.py
  tests/providers/gcp/internal/__init__.py
  tests/providers/gcp/internal/test_build.py
  tests/providers/gcp/internal/test_common.py
  tests/providers/gcp/internal/test_compute.py
  tests/providers/gcp/internal/test_compute_base_resource.py
  tests/providers/gcp/internal/test_gke.py
  tests/providers/gcp/internal/test_log.py
  tests/providers/gcp/internal/test_monitoring.py
  tests/providers/gcp/internal/test_storage.py
  tests/providers/gcp/test_forensics.py
  tests/run_tests.py
Labels: AWS, Azure, GCP, XL, cla: yes, cleanup

#240 Update CLI calls in AWS documentation
  docs/usermanual/index.md
Labels: AWS, S, cla: yes, documentation

#238 Wait for delete operation to complete in e2e cleanup
  tests/providers/azure/e2e.py
Labels: Azure, S, bug, cla: yes

#239 Update auto-generated docs
  docs/index.md
  docs/source/libcloudforensics.providers.aws.internal.rst
  docs/source/libcloudforensics.providers.azure.internal.rst
  docs/source/libcloudforensics.providers.azure.rst
  docs/source/libcloudforensics.providers.gcp.internal.rst
Labels: S, cla: yes, documentation

#250 Bump version
  libcloudforensics/__init__.py
Labels: cla: yes

#251 Fix try catch block
  libcloudforensics/providers/azure/internal/compute.py
  tests/providers/azure/internal/test_compute.py
Labels: Azure, S, bug, cla: yes

#252 Bump version
  libcloudforensics/__init__.py
Labels: cla: yes

#244 adding a default zone for a GCP project
  libcloudforensics/providers/gcp/internal/project.py
Labels: cla: yes

#256 Add ListBuckets method for #253
  libcloudforensics/providers/gcp/internal/storage.py
  tests/providers/gcp/gcp_mocks.py
  tests/providers/gcp/internal/test_storage.py
  tools/cli.py
  tools/gcp_cli.py
Labels: cla: yes

#257 Update codebase to latest pylint version
  libcloudforensics/errors.py
  libcloudforensics/logging_utils.py
  libcloudforensics/providers/aws/forensics.py
  libcloudforensics/providers/aws/internal/common.py
  libcloudforensics/providers/aws/internal/ebs.py
  libcloudforensics/providers/aws/internal/ec2.py
  libcloudforensics/providers/aws/internal/kms.py
  libcloudforensics/providers/azure/forensics.py
  libcloudforensics/providers/azure/internal/common.py
  libcloudforensics/providers/azure/internal/compute.py
  libcloudforensics/providers/azure/internal/monitoring.py
  libcloudforensics/providers/azure/internal/network.py
  libcloudforensics/providers/azure/internal/storage.py
  libcloudforensics/providers/gcp/forensics.py
  libcloudforensics/providers/gcp/internal/common.py
  libcloudforensics/providers/gcp/internal/compute.py
  libcloudforensics/providers/gcp/internal/compute_base_resource.py
  libcloudforensics/providers/gcp/internal/function.py
  libcloudforensics/scripts/utils.py
  tests/providers/aws/e2e.py
  tests/providers/azure/e2e.py
  tests/scripts/utils.py
  tools/az_cli.py
Labels: S, bug, cla: yes
