Repository google/cloud-forensics-utils, pull requests merged in 2021-07, with the labels that each got.

#327 Fix #326 - broken listinstances for Azure
  tools/az_cli.py
Labels: cla: yes

#329 Fix linter update
  .pylintrc
  libcloudforensics/providers/azure/internal/network.py
  tools/az_cli.py
  tools/gcp_cli.py
Labels: cla: yes

#328 Fetch `project_id` from the default() environment
  libcloudforensics/providers/gcp/internal/project.py
  tools/cli.py
  tools/gcp_cli.py
Labels: cla: yes

#330 Sanitise number of CPU requested in GetOrCreateVM in GCP
  libcloudforensics/providers/gcp/internal/compute.py
  tests/providers/gcp/internal/test_compute.py
Labels: cla: yes

#331 Add option to force delete instances that have deletion protection in place in GCP and AWS
  libcloudforensics/providers/aws/internal/ec2.py
  libcloudforensics/providers/gcp/internal/compute.py
  libcloudforensics/providers/gcp/internal/compute_base_resource.py
  tests/providers/aws/e2e.py
  tests/providers/aws/e2e_cli.py
  tools/aws_cli.py
  tools/cli.py
  tools/gcp_cli.py
Labels: cla: yes

#332 Add support for Azure CLI Auth
  .gitignore
  libcloudforensics/providers/azure/internal/common.py
  tests/providers/azure/azure_mocks.py
  tests/providers/azure/internal/test_common.py
  tests/scripts/test_azure_config_dir/accessTokens.json
  tests/scripts/test_azure_config_dir/azureProfile.json
Labels: cla: yes

#333 Update CODEOWNERS
  CODEOWNERS
Labels: cla: yes

#335 Query GCP logs with multiple projects
  libcloudforensics/providers/gcp/internal/log.py
  libcloudforensics/providers/gcp/internal/project.py
  tests/providers/gcp/gcp_mocks.py
  tests/providers/gcp/internal/test_log.py
  tools/cli.py
  tools/gcp_cli.py
Labels: cla: yes

#336 Cleanup GCP e2e CLI tests
  tests/providers/gcp/e2e_cli.py
  tests/providers/gcp/gcp_cli.py
Labels: cla: yes

#342 Do not cache the result of CreateService
  libcloudforensics/providers/gcp/internal/build.py
  libcloudforensics/providers/gcp/internal/cloudsql.py
  libcloudforensics/providers/gcp/internal/function.py
  libcloudforensics/providers/gcp/internal/gke.py
  libcloudforensics/providers/gcp/internal/log.py
  libcloudforensics/providers/gcp/internal/monitoring.py
  libcloudforensics/providers/gcp/internal/storage.py
Labels: cla: yes

#344 Fix pylint no-member
  libcloudforensics/providers/gcp/internal/build.py
  libcloudforensics/providers/gcp/internal/cloudsql.py
  libcloudforensics/providers/gcp/internal/function.py
  libcloudforensics/providers/gcp/internal/gke.py
  libcloudforensics/providers/gcp/internal/log.py
  libcloudforensics/providers/gcp/internal/monitoring.py
  libcloudforensics/providers/gcp/internal/storage.py
Labels: cla: yes

#334 Increase throttle sleep time
  libcloudforensics/providers/gcp/internal/common.py
Labels: cla: yes

#323 AWS: Copy an EBS snapshot into S3
  MANIFEST.in
  libcloudforensics/errors.py
  libcloudforensics/providers/aws/forensics.py
  libcloudforensics/providers/aws/internal/account.py
  libcloudforensics/providers/aws/internal/common.py
  libcloudforensics/providers/aws/internal/ec2.py
  libcloudforensics/providers/aws/internal/iam.py
  libcloudforensics/providers/aws/internal/iampolicies/ebs_copy_to_s3_policy.json
  libcloudforensics/providers/aws/internal/iampolicies/ec2_assume_role_policy.json
  libcloudforensics/providers/aws/internal/s3.py
  libcloudforensics/scripts/ebs_snapshot_copy_aws.sh
  libcloudforensics/scripts/utils.py
  tests/providers/aws/e2e.py
  tests/providers/aws/e2e_cli.py
  tests/providers/aws/internal/test_ec2.py
  tools/aws_cli.py
  tools/cli.py
Labels: AWS, XL, cla: yes

#343 Add GCP CPU usage
  libcloudforensics/providers/gcp/internal/monitoring.py
  tests/providers/gcp/gcp_mocks.py
  tests/providers/gcp/internal/test_monitoring.py
Labels: cla: yes

#346 Version bump for new release
  libcloudforensics/__init__.py
Labels: cla: yes

#345 Implement quarantinevm for AWS - issues/340
  libcloudforensics/providers/aws/forensics.py
  libcloudforensics/providers/aws/internal/ec2.py
  tests/providers/aws/aws_mocks.py
  tools/aws_cli.py
  tools/cli.py
Labels: AWS, cla: yes

#355 Fix Azure tests
  tests/providers/azure/internal/test_compute.py
Labels: cla: yes

#357 Change exponential backoff to calculated timeout for Snapshot S3 copy
  libcloudforensics/providers/aws/forensics.py
  libcloudforensics/providers/aws/internal/ec2.py
Labels: AWS, cla: yes

#356 S3 E2E test
  libcloudforensics/providers/aws/internal/ec2.py
  libcloudforensics/providers/aws/internal/s3.py
  tests/providers/aws/e2e.py
Labels: cla: yes

#351 Remove external IPs when putting an instance into network quarantine (GCP)
  libcloudforensics/providers/gcp/forensics.py
  libcloudforensics/providers/gcp/internal/compute.py
Labels: GCP, cla: yes

#358 Adjusted ebs snapshot s3 copy to wait for the instance health check
  libcloudforensics/providers/aws/forensics.py
Labels: cla: yes

#359 Revert 358, add wait for copy instance launch
  libcloudforensics/providers/aws/forensics.py
Labels: cla: yes

#360 Version bump for release
  libcloudforensics/__init__.py
Labels: cla: yes
